import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { ConvexClientProvider } from "@/components/providers/convex";
import { DashboardSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar";

const appSans = Inter({
  variable: "--font-app-sans",
  subsets: ["latin"],
});

const appMono = JetBrains_Mono({
  variable: "--font-app-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  return (
    <html lang="en">
      <body
        className={`${appSans.variable} ${appMono.variable} antialiased relative min-h-screen`}
      >
        <ConvexClientProvider>
          <SidebarProvider defaultOpen={defaultOpen}>
            <div className="relative flex h-screen w-full">
              <DashboardSidebar />
                {children}
            </div>
          </SidebarProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
